<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5pel5b+X');
$cfg_Cs[2]=array(0,2,1,'55u45YaM');
$cfg_Cs[3]=array(0,1,1,'6K+06K+0');
$cfg_Cs[4]=array(0,1,1,'6KeG6aKR');
$cfg_Cs[5]=array(0,1,1,'5YiG5Lqr');
$cfg_Cs[6]=array(0,1,1,'6Z+z5LmQ');
$cfg_Cs[7]=array(0,1,1,'55WZ6KiA5p2/');
$cfg_Cs[8]=array(0,1,1,'5Liq5Lq65qGj');
$cfg_Cs[9]=array(0,1,1,'5pu05aSa');
$cfg_Cs[10]=array(0,2,0,'572R56uZTE9HTw==');
$cfg_Cs[11]=array(0,1,1,'5b+D5oOF6K+0');
$cfg_Cs[12]=array(0,1,0,'5Zyo57q/55WZ6KiA');
?>