<?php
$z[0]=Array("arcurl","",62,77);
$z[1]=Array("title","",101,141);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",153,168);
$z[3]=Array("title","",202,242);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("arcurl","",324,339);
$z[5]=Array("title","",364,404);
$z[5][4]['function']="html2text(@me)";
$z[6]=Array("title","",409,489);
$z[6][4]['function']="(strlen(\"@me\")>39 ? cn_substr(\"@me\",39).\"...\" : \"@me\")";
$z[7]=Array("writer","",538,553);
$z[8]=Array("pubdate","",556,610);
$z[8][4]['function']="MyDate('Y年m月d日',@me)";
$z[9]=Array("click","",624,638);
$z[10]=Array("arcurl","",668,683);
$z[11]=Array("title","",704,744);
$z[11][4]['function']="html2text(@me)";
$z[12]=Array("id","",821,832);

?>