<li id="menu-item-2" class="menu-item menu-item-type-taxonomy menu-item-object-category {dede:field.currentstyle/} menu-item-2"><a href="{dede:field name='typeurl'/}">{dede:field name='typename'/}</a>
<ul class="sub-menu">{dede:channel type='son'}
	<li id="menu-item-3" class="menu-item menu-item-type-taxonomy menu-item-object-category menu-item-3"><a href="[field:typelink/]">[field:typename/]</a></li>{/dede:channel}
</ul>
</li>