<?php
$z[0]=Array("field","",88,114);
$z[0][4]['name']="currentstyle";
$z[1]=Array("field","",137,165);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",167,196);
$z[2][4]['name']="typename";
$z[3]=Array("channel","\n	<li id=\"menu-item-3\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>",222,419);
$z[3][4]['type']="son";

?>