<?php
$z[0]=Array("global","",42,66);
$z[0][4]['name']="itemindex";
$z[1]=Array("field","",87,115);
$z[1][4]['name']="typeurl";
$z[2]=Array("field","",133,162);
$z[2][4]['name']="typename";
$z[3]=Array("arclist","\n<li><div class=\"cmsflimg_box\"><div class=\"thumbnail\"><a href=\"[field:arcurl/]\" rel=\"bookmark\" title=\"[field:title function='html2text(@me)'/]\"><img src=\"[field:litpic/]\" width=\"80px\" height=\"57px\" alt=\"[field:title function='html2text(@me)'/]\"/></a></div></div><div class=\"cmsflimg_info\"><div class=\"cmsflimg_name\"><a href=\"[field:arcurl/]\" title=\"详细阅读 《[field:title function='html2text(@me)'/]》\">[field:title function='(strlen(\"@me\")>39 ? cn_substr(\"@me\",39).\"...\" : \"@me\")'/]</a></div><div class=\"cmsflimg_summary\">作者：[field:writer/] | [field:pubdate function=\"MyDate('Y年m月d日',@me)\"/]<br/>热度：[field:click/]次踩踏 | 评论：<a href=\"[field:arcurl/]#comments\" title=\"《[field:title function='html2text(@me)'/]》上的评论\"><script type=\"text/javascript\" src=\"/plus/feedcount.php?aid=[field:id/]\"></script></a></div></div></li>",205,1159);
$z[3][4]['row']="1";
$z[3][4]['flag']="a";
$z[3][4]['orderby']="pubdate";
$z[3][4]['type']="image.";
$z[3][4]['titlelen']="180";
$z[4]=Array("arclist","\n<li><span class=\"fr\">[field:pubdate function=\"MyDate('m-d',@me)\"/]</span><a href=\"[field:arcurl/]\" title=\"[field:title function='html2text(@me)'/]\">[field:title function='(strlen(\"@me\")>45 ? cn_substr(\"@me\",45).\"...\" : \"@me\")'/]</a></li>\n",1232,1548);
$z[4][4]['row']="5";
$z[4][4]['noflag']="a";
$z[4][4]['orderby']="pubdate";
$z[4][4]['titlelen']="180";

?>