<?php
$z[0]=Array("arcurl","",54,69);
$z[1]=Array("title","",93,133);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",145,160);
$z[3]=Array("title","",195,235);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("title","",291,371);
$z[4][4]['function']="(strlen(\"@me\")>24 ? cn_substr(\"@me\",24).\"...\" : \"@me\")";
$z[5]=Array("pubdate","",406,460);
$z[5][4]['function']="MyDate('y年m月d日',@me)";
$z[6]=Array("click","",495,509);
$z[7]=Array("arcurl","",556,571);
$z[8]=Array("title","",592,632);
$z[8][4]['function']="html2text(@me)";
$z[9]=Array("id","",709,720);

?>