<?php
$z[0]=Array("arcurl","",83,98);
$z[1]=Array("title","",122,162);
$z[1][4]['function']="html2text(@me)";
$z[2]=Array("litpic","",174,189);
$z[3]=Array("title","",225,265);
$z[3][4]['function']="html2text(@me)";
$z[4]=Array("arcurl","",342,357);
$z[5]=Array("title","",397,411);
$z[6]=Array("title","",416,496);
$z[6][4]['function']="(strlen(\"@me\")>60 ? cn_substr(\"@me\",60).\"...\" : \"@me\")";
$z[7]=Array("writer","",583,598);
$z[8]=Array("pubdate","",646,700);
$z[8][4]['function']="MyDate('Y年m月d日',@me)";
$z[9]=Array("click","",719,733);
$z[10]=Array("arcurl","",757,772);
$z[11]=Array("title","",793,807);
$z[12]=Array("id","",884,895);
$z[13]=Array("description","",950,1000);
$z[13][4]['function']="cn_substr(@me,110)";
$z[14]=Array("typeurl","",1059,1075);
$z[15]=Array("typename","",1091,1108);
$z[16]=Array("typename","",1126,1143);

?>