<?php
$z[0]=Array("channelartlist","\n<li id=\"menu-item-884\" class=\"menu-item menu-item-type-post_type menu-item-object-page menu-item-884\">  <a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a></li> \n",186,435);
$z[0][4]['typeid']="top";
$z[0][4]['row']="9";
$z[1]=Array("global","",496,522);
$z[1][4]['name']="cfg_powerby";
$z[2]=Array("global","",535,559);
$z[2][4]['name']="cfg_beian";
$z[3]=Array("global","",1025,1049);
$z[3][4]['name']="cfg_codes";

?>