<?php
$z[0]=Array("global","",132,159);
$z[0][4]['name']="cfg_basehost";
$z[1]=Array("global","",168,194);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("arclist","[field:litpic/]",206,298);
$z[2][4]['row']="1";
$z[2][4]['orderby']="pubdate";
$z[2][4]['type']="image.";
$z[2][4]['typeid']="10";
$z[3]=Array("global","",328,354);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("global","",492,522);
$z[4][4]['name']="cfg_description";
$z[5]=Array("global","",638,663);
$z[5][4]['name']="cfg_cmsurl";
$z[6]=Array("global","",1053,1077);
$z[6][4]['name']="cfg_email";
$z[7]=Array("global","",1186,1207);
$z[7][4]['name']="cfg_qq";
$z[8]=Array("global","",1314,1340);
$z[8][4]['name']="cfg_tencent";
$z[9]=Array("global","",1453,1476);
$z[9][4]['name']="cfg_sina";
$z[10]=Array("global","",1976,2001);
$z[10][4]['name']="cfg_cmsurl";
$z[11]=Array("channelartlist","\n<li id=\"menu-item-2\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category {dede:field.currentstyle/} menu-item-2\"><a href=\"{dede:field name='typeurl'/}\">{dede:field name='typename'/}</a>\n<ul class=\"sub-menu\">{dede:channel type='son'}\n	<li id=\"menu-item-3\" class=\"menu-item menu-item-type-taxonomy menu-item-object-category menu-item-3\"><a href=\"[field:typelink/]\">[field:typename/]</a></li>{/dede:channel}\n</ul>\n</li>\n",2020,2569);
$z[11][4]['typeid']="top";
$z[11][4]['row']="9";
$z[11][4]['currentstyle']="current-menu-item current_page_item";

?>